site_name: daftlistings
theme: readthedocs
site_author: Anthony Bloomer
site_description: A web scraper for Daft.ie
extra:
    theme_inverse: true
repo_url: https://github.com/anthonybloomer/daftlistings
pages:
- Home: index.md
